//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database_Ado_Session
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp
    {
        public int Eid { get; set; }
        public string Ename { get; set; }
        public string Edeig { get; set; }
        public Nullable<double> Esalary { get; set; }
        public Nullable<System.DateTime> Doj { get; set; }
    }
}
